// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var aws, config, dynamo;

  aws = require('aws-sdk');

  dynamo = require('dynamodb-doc');

  config = require('./config');

  aws.config.credentials = new aws.SharedIniFileCredentials({
    profile: config.aws.access.profile
  });

  aws.config.apiVersions = {
    dynamodb: config.aws.ddb.version
  };

  aws.config.update({
    region: config.aws.access.region
  });

  if (typeof module !== "undefined" && module !== null) {
    module.exports = {
      ddb: new dynamo.DynamoDB(new aws.DynamoDB())
    };
  }

}).call(this);
