// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  if (typeof module !== "undefined" && module !== null) {
    module.exports = {
      app: {
        enable: ['strict routing', 'trust proxy']
      },
      misc: {
        pong: 'You have received a singular pong.'
      },
      proc: {
        port: {
          http: 5056,
          https: 5058
        },
        title: 'NODE_KITCHEN_SINK'
      }
    };
  }

}).call(this);
