// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var middleware;

  middleware = {
    noCache: function(req, res, next) {
      res.set({
        'Cache-Control': 'private, no-cache, no-store, must-revalidate',
        'Expires': '-1',
        'Pragma': 'no-cache'
      });
      return next();
    },
    httpsRedirect: function(req, res, next) {
      var host;
      if (!req.secure && req.hostname !== 'localhost') {
        host = req.get('host');
        return res.redirect(308, "https://" + host + req.originalUrl);
      } else {
        return next();
      }
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = middleware;
  }

}).call(this);
