// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var app, bodyParser, config, dieWithHonor, express, http, httpPort, httpServer, i, jmoc, len, method, methods, middleware, ref, route, routes, setting, url;

  bodyParser = require('body-parser');

  express = require('express');

  http = require('http');

  config = require('./config');

  middleware = require('./middleware');

  routes = require('./routes');

  jmoc = require('./jmoc');

  process.title = config.proc.title;

  app = express();

  ref = config.app.enable;
  for (i = 0, len = ref.length; i < len; i++) {
    setting = ref[i];
    app.enable(setting);
  }

  app.use(middleware.httpsRedirect);

  app.use('/jmoc', jmoc);

  for (url in routes) {
    methods = routes[url];
    for (method in methods) {
      route = methods[method];
      if (route.hasOwnProperty('middleware')) {
        route.middleware.forEach(function(mw) {
          return app[method](url, mw);
        });
      }
      app[method](url, route.handler);
    }
  }

  httpServer = http.createServer(app);

  httpPort = config.proc.port.http;

  dieWithHonor = function() {
    var die;
    die = function(err) {
      if (err) {
        console.error(err);
        return process.exit(1);
      } else {
        return process.exit(0);
      }
    };
    return httpServer.close(die);
  };

  process.on('SIGINT', dieWithHonor);

  process.on('SIGTERM', dieWithHonor);

  httpServer.listen(httpPort);

}).call(this);
