// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  var config, middleware;

  config = require('./config');

  middleware = {
    noCache: function(req, res, next) {
      res.set({
        'Cache-Control': 'private, no-cache, no-store, must-revalidate',
        'Expires': '-1',
        'Pragma': 'no-cache'
      });
      return next();
    },
    accessControl: function(req, res, next) {
      res.set(config.app.access);
      return next();
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = middleware;
  }

}).call(this);
